### ISSUE TITLE
Create context but timeout?

### ISSUE THREAD

**Issue by seraphliu** [ooyala/spark-jobserver#15]
Hi,
I got a timeout error when I tried to create a new context with curl. Has anyone run into the same problem?
#### Details:

As described in the README.md, I tried to create a new conext with curl:

```
curl -d "" 'localhost:8090/contexts/test-context?num-cpu-cores=4&mem-per-node=512m'
```

And the error msg:

```
The server was not able to produce a timely response to your request.
```

From the job-server.log, it seems that the ContextInitialized message was not sent back successfully.

```
INFO  a.actor.DeadLetterActorRef [] [akka://JobServer/deadLetters] - Message 
[spark.jobserver.ContextSupervisor$ContextInitialized$] from Actor[akka://JobServer
/user/context-supervisor#-638835727] to Actor[akka://JobServer/deadLetters] was 
not delivered. [1] dead letters encountered. This logging can be turned off or 
adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-
letters-during-shutdown'.
```

**Comment by Murukaen** [comment]
Hello. I have the same issue as described by @SeraphLiu, however, my context is not created. The logs are: 

> [2016-07-01 12:37:26,484] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Starting context with actor name jobManager-a3-a071-6c40c2ca38e5
> [2016-07-01 12:37:26,485] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Created working directory /logs/spark-jobserver/test/jobserver-cdr-filtering-context3587230052834289175 for context cdr-filtering-context
> [2016-07-01 12:37:26,485] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Starting to execute sub process [./manager_start.sh, /logs/spark-jobserver/test/jobserver-cdr-filtering-context3587230052834289175, akka.tcp://JobServer@127.0.0.1:45748]
> [2016-07-01 12:37:28,646] INFO  Cluster(akka://JobServer) [] [Cluster(akka://JobServer)] - Cluster Node [akka.tcp://JobServer@127.0.0.1:45748] - Node [akka.tcp://JobServer@127.0.0.1:59577] is JOINING, roles [manager]
> [2016-07-01 12:37:31,637] INFO  AkkaClusterSupervisorActor [] [akka://JobServer/user/context-supervisor] - Received identify response, attempting to initialize context at akka.tcp://JobServer@127.0.0.1:59577/user/*
> [2016-07-01 12:37:31,637] INFO  k.jobserver.JobResultActor [] [akka://JobServer/user/context-supervisor/$e] - Starting actor spark.jobserver.JobResultActor
> [2016-07-01 12:38:31,651] INFO  AkkaClusterSupervisorActor [] [] - Failed to send initialize message to context Actor[akka.tcp://JobServer@127.0.0.1:59577/user/jobManager-a3-a071-6c40c2ca38e5#1819672480]
> akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka.tcp://JobServer@127.0.0.1:59577/user/jobManager-a3-a071-6c40c2ca38e5#1819672480]] after [60000 ms]
> 	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:333)
> 	at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
> 	at scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)
> 	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)
> 	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
> 	at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
> 	at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
> 	at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
> 	at java.lang.Thread.run(Thread.java:745)
> [2016-07-01 12:38:31,652] INFO  r$RemoteDeadLetterActorRef [] [akka://JobServer/deadLetters] - Message [spark.jobserver.ContextSupervisor$ContextInitError] from Actor[akka://JobServer/user/context-supervisor#1365847561] to Actor[akka://JobServer/deadLetters] was not delivered. [4] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

Your assistance is much appreciated.

**Comment by hzxjtx** [comment]
{
  "status": "CONTEXT INIT ERROR",
  "result": {
    "message": "Ask timed out on [Actor[akka.tcp://JobServer@127.0.0.1:33597/user/jobManager-c8-97dd-1d1ab28eee9c#1009187955]] after [60000 ms]",
    "errorClass": "akka.pattern.AskTimeoutException",
    "stack": ["akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)", "akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)", "scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)", "scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)", "akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)", "akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)", "akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)", "akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)", "java.lang.Thread.run(Thread.java:745)"]
  }


context init error !!!!!
